### ISSUE TITLE
AttributeError: 'module' object has no attribute 'theilslopes'

### ISSUE THREAD

**Issue by talaikis** [welch/seasonal#3]
File "/usr/local/lib/python2.7/dist-packages/seasonal/trend.py", line 121, in aglet
    leftslope = stats.theilslopes(src[: window])[0]
AttributeError: 'module' object has no attribute 'theilslopes'

Using scipy 0.13.3

**Comment by welch** [comment]
that's a pretty ancient scipy, I developed under 0.17.0
looks like I should establish some minimum versions in the requirements.
