### ISSUE TITLE
memory consumption is high

### ISSUE THREAD

**Issue by rotten** [welch/seasonal#5]
I tried running a csv file which has 14,000 rows in it through the seasonal command line.  (Hourly data going back a few months, with simple integer values [1<x<1000].)  I had 10G free on my laptop when I did so.  All of it was consumed and I had to kill seasonal to get my laptop resources back.

14K rows doesn't seem like a lot of data.

What is the practical limit for number of rows of TS data that we can process with this on a modest 16G laptop?  Do you have any tips for processing data sets of this size or bigger?

I have not yet tried to figure out which part of the processing is so memory intensive.  I thought I'd raise the issue here while I was investigating further.

**Comment by welch** [comment]
I am betting you have automatic period detection turned on, and the periodogram is blowing up. 14K rows is pretty excessive for automatic period detection. I'm too swamped this week to have a confirming look, but if you know the periodicity best to supply it...

**Comment by rotten** [comment]
Yes.  As soon as I specify a period, it completes within seconds and does not consume my entire laptop.  Thanks!
