### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by marchezinixd** [welch/seasonal#7]
When i have a column with missing data, it try to fit the season and the memory consumption tend to crash my PC. This is an expected behaviour?
I would like to know if it's possible to fit the season with time not equidistant, for example, i have a whole month, but day 25 is missing.
I'm using the library passing a vector, this way i know that it will only work with equidistant time difference, there is another way?
Thanks.

**Comment by welch** [comment]
unevenly spaced data is a big can of worms, too much for this simple package to take on.
